import type { Metadata } from "next";
import { Geist, Geist_Mono,Roboto,Poppins,Yantramanav } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav/TopNav";
import Footer from "@/components/Footer/Footer";
import QueryProvider from "@/components/providers/QueryProvider";
import ChatBotButton from "@/components/ChatbotButton/ChatbotButton";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],        
  weight: ["400", "500", "700"],
  variable: "--font-roboto", // Tailwind variable
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins", // Tailwind variable
});
const yantramanav = Yantramanav({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-yantramanav", // Tailwind variable
});


export const metadata: Metadata = {
  title: "CortechSols",
  description: "Generated by create next app",
   icons: {
    icon: "/favicon.png", // Default favicon
    shortcut: "/favicon.png",
    apple: "/favicon.png",

  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${poppins.variable} ${yantramanav.variable} antialiased max-w-[1920px] mx-auto`}
      >
        <QueryProvider>
          <TopNav />
          {children}
          {/* <ChatBotButton /> */}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
